name: hackmate

services:
  chat_db:
    image: postgres:18
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-hackmate_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-hackmate_password}
      POSTGRES_DB: ${POSTGRES_DB:-db}
    volumes:
      - db_chat_data:/var/lib/postgresql

volumes:
  db_chat_data:
    name: hackmate_db_chat_data
